### PR TITLE
chore: add sanitary actions

### PR DESCRIPTION
**Pull request by nimakaviani**
- add dependabot for version bumps
- add linting for PRs
- update package info

### CODE REVIEW

**Comment by nimakaviani** [comment]
This PR can go in once approved. I separated the release bits into PR #7

**Comment by niallthomson** [comment]
Same question on this PR I guess, still skipping?

https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/main/.github/workflows/upgrade-backstage.yml

**Comment by nimakaviani** [comment]
yeah not completely sold yet. I think a broken main branch that we cant tell is broken still bugs me. particularly with a green checkmark we get from running the units.

**Comment by niallthomson** [comment]
Addressed separately

**Pull request closed without merging**
